/********************************************************************************
** Form generated from reading UI file 'setupform.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SETUPFORM_H
#define UI_SETUPFORM_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_setupForm
{
public:
    QLabel *labelTarget;
    QLabel *labelMono;
    QLabel *labelEdge;
    QLabel *labelHough;
    QLabel *labelAnalyze;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QPushButton *captureButton;
    QPushButton *saveButton;
    QLabel *labelPrimaryLine;
    QPushButton *saveExitButton;
    QPushButton *exitButton;
    QFrame *line_2;
    QPushButton *captureButton_2;
    QSlider *brightnessSlider;
    QLabel *labelBrightness;
    QSlider *contrastSlider;
    QLabel *labelContrast;
    QSlider *gammaSlider;
    QLabel *labelGamma;
    QPushButton *brightnessReset;
    QPushButton *contrastReset;
    QPushButton *gammaReset;
    QSlider *fileSlider;
    QCheckBox *checkProcessing;
    QComboBox *edgeDetectionBox;
    QLabel *label_11;
    QLabel *label_17;
    QLabel *label_18;
    QCheckBox *cameraEnhancementsBox;
    QPushButton *captureNext;
    QPushButton *capturePrev;
    QCheckBox *debugModeBox;
    QLabel *labelPicNo;
    QTabWidget *tabWidget;
    QWidget *tab;
    QPlainTextEdit *plainTextEdit;
    QPushButton *clearButton;
    QLabel *labelMainEdgesNumber;
    QLabel *label_19;
    QLabel *label_21;
    QSlider *gaussSizeSlider;
    QLabel *label_9;
    QCheckBox *lineDetectionBox;
    QLineEdit *editHoughThetaMax;
    QRadioButton *radioWoLaser;
    QComboBox *algorithmBox;
    QRadioButton *radioLaser;
    QSlider *mainEdgesSlider;
    QCheckBox *cannyThinningBox;
    QLabel *label_8;
    QLabel *labelGaussSDev;
    QLabel *label_20;
    QLineEdit *editHoughLineNo;
    QLabel *labelGaussSize;
    QLineEdit *editHoughThetaStep;
    QSlider *gaussSDevSlider;
    QLabel *label_6;
    QLineEdit *editHoughThetaMin;
    QLineEdit *editLineScore;
    QLineEdit *editHoughThetaMaxSub;
    QLineEdit *editHoughThreshold;
    QLabel *label_10;
    QLabel *label_7;
    QLabel *labelVoteAvg;
    QLineEdit *editVoidThreshold;
    QLineEdit *editHoughThetaMinSub;
    QCheckBox *checkSubImage;
    QLineEdit *editHoughThetaStepSub;
    QCheckBox *readWeldSeamBox;
    QCheckBox *readMachineStatusBox;
    QCheckBox *readDistanceBox;
    QLabel *label_15;
    QCheckBox *alignGuideBox;
    QCheckBox *zctrlBox;
    QCheckBox *hardControlStartBox;
    QCheckBox *dynamicAlgoBox;
    QCheckBox *widthControlBox;
    QCheckBox *timeControlBox;
    QLabel *label_16;
    QLabel *label_13;
    QLineEdit *editIPI;
    QLineEdit *editVideoDuration;
    QLabel *label_14;
    QLineEdit *editFPS;
    QLabel *label_22;
    QCheckBox *twoPassWeldingBox;
    QCheckBox *autoDetect2ndPassBox;
    QWidget *tab_2;
    QGraphicsView *graphicsView;
    QGraphicsView *graphicsView2;
    QGraphicsView *graphicsView3;
    QLabel *labelTarget2;
    QLabel *label_23;
    QPushButton *imgParametersButton;
    QPushButton *testButton;
    QLabel *label_24;
    QSlider *maFilterSizeSlider;
    QLabel *labelMAFilterSize;
    QPushButton *histogramAnalysisButton;
    QLabel *label_25;
    QSlider *histAngleSlider;
    QLabel *labelHistAngle;
    QRadioButton *radioGray;
    QRadioButton *radioColored;
    QLabel *label_26;
    QSlider *lenRateThrSlider;
    QLabel *labellenRateThr;
    QSlider *bandWidthMinSlider;
    QLabel *label_27;
    QLabel *labelBandWidthMin;
    QLabel *label_28;
    QSlider *bandCenterMaxSlider;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *labelBandCenterMax;
    QSlider *histAreaNoSlider;
    QLabel *labelHistAreaNo;
    QLabel *label_31;
    QComboBox *regionBox;
    QLabel *labelhistCornerPrec;
    QLabel *label_32;
    QSlider *histCornerPrecSlider;
    QButtonGroup *colorGrayGroup;
    QButtonGroup *laserGroup;

    void setupUi(QWidget *setupForm)
    {
        if (setupForm->objectName().isEmpty())
            setupForm->setObjectName(QStringLiteral("setupForm"));
        setupForm->setWindowModality(Qt::WindowModal);
        setupForm->resize(1630, 750);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(setupForm->sizePolicy().hasHeightForWidth());
        setupForm->setSizePolicy(sizePolicy);
        setupForm->setMinimumSize(QSize(1630, 750));
        setupForm->setMaximumSize(QSize(1630, 750));
        setupForm->setContextMenuPolicy(Qt::DefaultContextMenu);
        QIcon icon;
        icon.addFile(QStringLiteral(":/resources/Weather-icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        setupForm->setWindowIcon(icon);
        labelTarget = new QLabel(setupForm);
        labelTarget->setObjectName(QStringLiteral("labelTarget"));
        labelTarget->setGeometry(QRect(10, 52, 320, 320));
        labelTarget->setFrameShape(QFrame::Box);
        labelTarget->setScaledContents(true);
        labelMono = new QLabel(setupForm);
        labelMono->setObjectName(QStringLiteral("labelMono"));
        labelMono->setGeometry(QRect(333, 52, 320, 320));
        labelMono->setFrameShape(QFrame::Box);
        labelMono->setScaledContents(true);
        labelEdge = new QLabel(setupForm);
        labelEdge->setObjectName(QStringLiteral("labelEdge"));
        labelEdge->setGeometry(QRect(656, 52, 320, 320));
        labelEdge->setFrameShape(QFrame::Box);
        labelEdge->setScaledContents(true);
        labelHough = new QLabel(setupForm);
        labelHough->setObjectName(QStringLiteral("labelHough"));
        labelHough->setGeometry(QRect(333, 410, 320, 320));
        labelHough->setFrameShape(QFrame::Box);
        labelHough->setScaledContents(true);
        labelAnalyze = new QLabel(setupForm);
        labelAnalyze->setObjectName(QStringLiteral("labelAnalyze"));
        labelAnalyze->setGeometry(QRect(656, 410, 320, 320));
        labelAnalyze->setFrameShape(QFrame::Box);
        labelAnalyze->setScaledContents(true);
        label = new QLabel(setupForm);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 32, 111, 16));
        label->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        label_2 = new QLabel(setupForm);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(333, 32, 111, 16));
        label_2->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        label_3 = new QLabel(setupForm);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(656, 32, 141, 16));
        label_3->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        label_4 = new QLabel(setupForm);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(333, 390, 81, 16));
        label_4->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        label_5 = new QLabel(setupForm);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(656, 390, 91, 16));
        label_5->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        captureButton = new QPushButton(setupForm);
        captureButton->setObjectName(QStringLiteral("captureButton"));
        captureButton->setGeometry(QRect(9, 374, 91, 25));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        captureButton->setFont(font);
        saveButton = new QPushButton(setupForm);
        saveButton->setObjectName(QStringLiteral("saveButton"));
        saveButton->setGeometry(QRect(109, 374, 91, 25));
        saveButton->setFont(font);
        labelPrimaryLine = new QLabel(setupForm);
        labelPrimaryLine->setObjectName(QStringLiteral("labelPrimaryLine"));
        labelPrimaryLine->setEnabled(true);
        labelPrimaryLine->setGeometry(QRect(474, 390, 171, 20));
        labelPrimaryLine->setFont(font);
        labelPrimaryLine->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelPrimaryLine->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        saveExitButton = new QPushButton(setupForm);
        saveExitButton->setObjectName(QStringLiteral("saveExitButton"));
        saveExitButton->setGeometry(QRect(731, 3, 100, 25));
        saveExitButton->setFont(font);
        saveExitButton->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        exitButton = new QPushButton(setupForm);
        exitButton->setObjectName(QStringLiteral("exitButton"));
        exitButton->setGeometry(QRect(840, 3, 100, 25));
        exitButton->setFont(font);
        exitButton->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        line_2 = new QFrame(setupForm);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(333, 372, 320, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        captureButton_2 = new QPushButton(setupForm);
        captureButton_2->setObjectName(QStringLiteral("captureButton_2"));
        captureButton_2->setGeometry(QRect(9, 6, 101, 25));
        captureButton_2->setFont(font);
        brightnessSlider = new QSlider(setupForm);
        brightnessSlider->setObjectName(QStringLiteral("brightnessSlider"));
        brightnessSlider->setGeometry(QRect(69, 421, 160, 22));
        brightnessSlider->setAutoFillBackground(false);
        brightnessSlider->setMinimum(-30);
        brightnessSlider->setMaximum(30);
        brightnessSlider->setSingleStep(5);
        brightnessSlider->setTracking(true);
        brightnessSlider->setOrientation(Qt::Horizontal);
        brightnessSlider->setInvertedAppearance(false);
        brightnessSlider->setInvertedControls(false);
        brightnessSlider->setTickPosition(QSlider::TicksBothSides);
        brightnessSlider->setTickInterval(10);
        labelBrightness = new QLabel(setupForm);
        labelBrightness->setObjectName(QStringLiteral("labelBrightness"));
        labelBrightness->setGeometry(QRect(238, 421, 42, 20));
        labelBrightness->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelBrightness->setFrameShape(QFrame::Box);
        labelBrightness->setAlignment(Qt::AlignCenter);
        contrastSlider = new QSlider(setupForm);
        contrastSlider->setObjectName(QStringLiteral("contrastSlider"));
        contrastSlider->setGeometry(QRect(69, 446, 160, 22));
        contrastSlider->setMinimum(0);
        contrastSlider->setMaximum(200);
        contrastSlider->setSingleStep(10);
        contrastSlider->setValue(100);
        contrastSlider->setTracking(true);
        contrastSlider->setOrientation(Qt::Horizontal);
        contrastSlider->setTickPosition(QSlider::TicksBothSides);
        contrastSlider->setTickInterval(50);
        labelContrast = new QLabel(setupForm);
        labelContrast->setObjectName(QStringLiteral("labelContrast"));
        labelContrast->setGeometry(QRect(238, 446, 42, 20));
        labelContrast->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelContrast->setFrameShape(QFrame::Box);
        labelContrast->setAlignment(Qt::AlignCenter);
        gammaSlider = new QSlider(setupForm);
        gammaSlider->setObjectName(QStringLiteral("gammaSlider"));
        gammaSlider->setGeometry(QRect(69, 471, 160, 22));
        gammaSlider->setMinimum(0);
        gammaSlider->setMaximum(200);
        gammaSlider->setSingleStep(10);
        gammaSlider->setValue(100);
        gammaSlider->setTracking(true);
        gammaSlider->setOrientation(Qt::Horizontal);
        gammaSlider->setTickPosition(QSlider::TicksBothSides);
        gammaSlider->setTickInterval(50);
        labelGamma = new QLabel(setupForm);
        labelGamma->setObjectName(QStringLiteral("labelGamma"));
        labelGamma->setGeometry(QRect(238, 471, 42, 20));
        labelGamma->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelGamma->setFrameShape(QFrame::Box);
        labelGamma->setAlignment(Qt::AlignCenter);
        brightnessReset = new QPushButton(setupForm);
        brightnessReset->setObjectName(QStringLiteral("brightnessReset"));
        brightnessReset->setGeometry(QRect(286, 421, 42, 22));
        brightnessReset->setFont(font);
        contrastReset = new QPushButton(setupForm);
        contrastReset->setObjectName(QStringLiteral("contrastReset"));
        contrastReset->setGeometry(QRect(286, 446, 42, 22));
        contrastReset->setFont(font);
        gammaReset = new QPushButton(setupForm);
        gammaReset->setObjectName(QStringLiteral("gammaReset"));
        gammaReset->setGeometry(QRect(286, 471, 42, 22));
        gammaReset->setFont(font);
        fileSlider = new QSlider(setupForm);
        fileSlider->setObjectName(QStringLiteral("fileSlider"));
        fileSlider->setEnabled(false);
        fileSlider->setGeometry(QRect(129, 8, 191, 22));
        fileSlider->setOrientation(Qt::Horizontal);
        checkProcessing = new QCheckBox(setupForm);
        checkProcessing->setObjectName(QStringLiteral("checkProcessing"));
        checkProcessing->setEnabled(false);
        checkProcessing->setGeometry(QRect(399, 10, 101, 17));
        edgeDetectionBox = new QComboBox(setupForm);
        edgeDetectionBox->setObjectName(QStringLiteral("edgeDetectionBox"));
        edgeDetectionBox->setGeometry(QRect(855, 375, 121, 22));
        label_11 = new QLabel(setupForm);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(9, 421, 51, 20));
        QFont font1;
        font1.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font1.setPointSize(8);
        font1.setBold(false);
        font1.setWeight(50);
        label_11->setFont(font1);
        label_11->setFrameShape(QFrame::NoFrame);
        label_11->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        label_17 = new QLabel(setupForm);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(9, 446, 51, 20));
        label_17->setFont(font1);
        label_17->setFrameShape(QFrame::NoFrame);
        label_17->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        label_18 = new QLabel(setupForm);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(9, 471, 51, 20));
        label_18->setFont(font1);
        label_18->setFrameShape(QFrame::NoFrame);
        label_18->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        cameraEnhancementsBox = new QCheckBox(setupForm);
        cameraEnhancementsBox->setObjectName(QStringLiteral("cameraEnhancementsBox"));
        cameraEnhancementsBox->setGeometry(QRect(141, 401, 71, 17));
        QFont font2;
        font2.setPointSize(8);
        font2.setBold(false);
        font2.setWeight(50);
        cameraEnhancementsBox->setFont(font2);
        captureNext = new QPushButton(setupForm);
        captureNext->setObjectName(QStringLiteral("captureNext"));
        captureNext->setEnabled(false);
        captureNext->setGeometry(QRect(359, 6, 25, 25));
        captureNext->setFont(font);
        capturePrev = new QPushButton(setupForm);
        capturePrev->setObjectName(QStringLiteral("capturePrev"));
        capturePrev->setEnabled(false);
        capturePrev->setGeometry(QRect(329, 6, 25, 25));
        capturePrev->setFont(font);
        debugModeBox = new QCheckBox(setupForm);
        debugModeBox->setObjectName(QStringLiteral("debugModeBox"));
        debugModeBox->setGeometry(QRect(209, 378, 71, 17));
        debugModeBox->setFont(font2);
        labelPicNo = new QLabel(setupForm);
        labelPicNo->setObjectName(QStringLiteral("labelPicNo"));
        labelPicNo->setGeometry(QRect(479, 10, 150, 16));
        labelPicNo->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        labelPicNo->setAlignment(Qt::AlignCenter);
        tabWidget = new QTabWidget(setupForm);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(980, 10, 635, 721));
        tabWidget->setTabPosition(QTabWidget::West);
        tabWidget->setUsesScrollButtons(false);
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        plainTextEdit = new QPlainTextEdit(tab);
        plainTextEdit->setObjectName(QStringLiteral("plainTextEdit"));
        plainTextEdit->setGeometry(QRect(3, 3, 600, 208));
        QFont font3;
        font3.setFamily(QStringLiteral("Tahoma"));
        plainTextEdit->setFont(font3);
        plainTextEdit->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 195);"));
        clearButton = new QPushButton(tab);
        clearButton->setObjectName(QStringLiteral("clearButton"));
        clearButton->setGeometry(QRect(512, 213, 90, 25));
        clearButton->setFont(font);
        labelMainEdgesNumber = new QLabel(tab);
        labelMainEdgesNumber->setObjectName(QStringLiteral("labelMainEdgesNumber"));
        labelMainEdgesNumber->setGeometry(QRect(300, 350, 42, 20));
        labelMainEdgesNumber->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelMainEdgesNumber->setFrameShape(QFrame::Box);
        labelMainEdgesNumber->setAlignment(Qt::AlignCenter);
        label_19 = new QLabel(tab);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(19, 292, 91, 20));
        label_19->setFont(font1);
        label_19->setFrameShape(QFrame::NoFrame);
        label_19->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        label_21 = new QLabel(tab);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(-10, 353, 121, 20));
        label_21->setFont(font1);
        label_21->setFrameShape(QFrame::NoFrame);
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        gaussSizeSlider = new QSlider(tab);
        gaussSizeSlider->setObjectName(QStringLiteral("gaussSizeSlider"));
        gaussSizeSlider->setGeometry(QRect(120, 292, 160, 22));
        gaussSizeSlider->setAutoFillBackground(false);
        gaussSizeSlider->setMinimum(1);
        gaussSizeSlider->setMaximum(5);
        gaussSizeSlider->setSingleStep(1);
        gaussSizeSlider->setValue(1);
        gaussSizeSlider->setSliderPosition(1);
        gaussSizeSlider->setTracking(true);
        gaussSizeSlider->setOrientation(Qt::Horizontal);
        gaussSizeSlider->setInvertedAppearance(false);
        gaussSizeSlider->setInvertedControls(false);
        gaussSizeSlider->setTickPosition(QSlider::TicksBothSides);
        gaussSizeSlider->setTickInterval(1);
        label_9 = new QLabel(tab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(120, 470, 111, 20));
        QFont font4;
        font4.setBold(false);
        font4.setWeight(50);
        label_9->setFont(font4);
        label_9->setFrameShape(QFrame::NoFrame);
        label_9->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        lineDetectionBox = new QCheckBox(tab);
        lineDetectionBox->setObjectName(QStringLiteral("lineDetectionBox"));
        lineDetectionBox->setGeometry(QRect(150, 382, 131, 16));
        lineDetectionBox->setFont(font2);
        lineDetectionBox->setLayoutDirection(Qt::RightToLeft);
        editHoughThetaMax = new QLineEdit(tab);
        editHoughThetaMax->setObjectName(QStringLiteral("editHoughThetaMax"));
        editHoughThetaMax->setGeometry(QRect(290, 468, 42, 20));
        editHoughThetaMax->setAlignment(Qt::AlignCenter);
        radioWoLaser = new QRadioButton(tab);
        laserGroup = new QButtonGroup(setupForm);
        laserGroup->setObjectName(QStringLiteral("laserGroup"));
        laserGroup->addButton(radioWoLaser);
        radioWoLaser->setObjectName(QStringLiteral("radioWoLaser"));
        radioWoLaser->setGeometry(QRect(202, 239, 111, 21));
        radioWoLaser->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        algorithmBox = new QComboBox(tab);
        algorithmBox->setObjectName(QStringLiteral("algorithmBox"));
        algorithmBox->setGeometry(QRect(120, 265, 221, 22));
        radioLaser = new QRadioButton(tab);
        laserGroup->addButton(radioLaser);
        radioLaser->setObjectName(QStringLiteral("radioLaser"));
        radioLaser->setGeometry(QRect(82, 239, 103, 21));
        radioLaser->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        radioLaser->setChecked(true);
        mainEdgesSlider = new QSlider(tab);
        mainEdgesSlider->setObjectName(QStringLiteral("mainEdgesSlider"));
        mainEdgesSlider->setGeometry(QRect(120, 352, 160, 22));
        mainEdgesSlider->setAutoFillBackground(false);
        mainEdgesSlider->setMinimum(1);
        mainEdgesSlider->setMaximum(5);
        mainEdgesSlider->setSingleStep(1);
        mainEdgesSlider->setValue(1);
        mainEdgesSlider->setSliderPosition(1);
        mainEdgesSlider->setTracking(true);
        mainEdgesSlider->setOrientation(Qt::Horizontal);
        mainEdgesSlider->setInvertedAppearance(false);
        mainEdgesSlider->setInvertedControls(false);
        mainEdgesSlider->setTickPosition(QSlider::TicksBothSides);
        mainEdgesSlider->setTickInterval(1);
        cannyThinningBox = new QCheckBox(tab);
        cannyThinningBox->setObjectName(QStringLiteral("cannyThinningBox"));
        cannyThinningBox->setGeometry(QRect(120, 410, 161, 17));
        cannyThinningBox->setFont(font2);
        cannyThinningBox->setLayoutDirection(Qt::RightToLeft);
        label_8 = new QLabel(tab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(120, 500, 111, 20));
        label_8->setFont(font4);
        label_8->setFrameShape(QFrame::NoFrame);
        label_8->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        labelGaussSDev = new QLabel(tab);
        labelGaussSDev->setObjectName(QStringLiteral("labelGaussSDev"));
        labelGaussSDev->setGeometry(QRect(300, 320, 42, 20));
        labelGaussSDev->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelGaussSDev->setFrameShape(QFrame::Box);
        labelGaussSDev->setAlignment(Qt::AlignCenter);
        label_20 = new QLabel(tab);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(9, 322, 101, 20));
        label_20->setFont(font1);
        label_20->setFrameShape(QFrame::NoFrame);
        label_20->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        editHoughLineNo = new QLineEdit(tab);
        editHoughLineNo->setObjectName(QStringLiteral("editHoughLineNo"));
        editHoughLineNo->setGeometry(QRect(240, 438, 42, 20));
        editHoughLineNo->setAlignment(Qt::AlignCenter);
        labelGaussSize = new QLabel(tab);
        labelGaussSize->setObjectName(QStringLiteral("labelGaussSize"));
        labelGaussSize->setGeometry(QRect(300, 290, 42, 20));
        labelGaussSize->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelGaussSize->setFrameShape(QFrame::Box);
        labelGaussSize->setAlignment(Qt::AlignCenter);
        editHoughThetaStep = new QLineEdit(tab);
        editHoughThetaStep->setObjectName(QStringLiteral("editHoughThetaStep"));
        editHoughThetaStep->setGeometry(QRect(240, 498, 42, 20));
        editHoughThetaStep->setAlignment(Qt::AlignCenter);
        gaussSDevSlider = new QSlider(tab);
        gaussSDevSlider->setObjectName(QStringLiteral("gaussSDevSlider"));
        gaussSDevSlider->setGeometry(QRect(120, 322, 160, 22));
        gaussSDevSlider->setAutoFillBackground(false);
        gaussSDevSlider->setMinimum(1);
        gaussSDevSlider->setMaximum(20);
        gaussSDevSlider->setSingleStep(1);
        gaussSDevSlider->setValue(10);
        gaussSDevSlider->setSliderPosition(10);
        gaussSDevSlider->setTracking(true);
        gaussSDevSlider->setOrientation(Qt::Horizontal);
        gaussSDevSlider->setInvertedAppearance(false);
        gaussSDevSlider->setInvertedControls(false);
        gaussSDevSlider->setTickPosition(QSlider::TicksBothSides);
        gaussSDevSlider->setTickInterval(5);
        label_6 = new QLabel(tab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(120, 440, 111, 20));
        label_6->setFont(font4);
        label_6->setFrameShape(QFrame::NoFrame);
        label_6->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        editHoughThetaMin = new QLineEdit(tab);
        editHoughThetaMin->setObjectName(QStringLiteral("editHoughThetaMin"));
        editHoughThetaMin->setGeometry(QRect(240, 468, 42, 20));
        editHoughThetaMin->setAlignment(Qt::AlignCenter);
        editLineScore = new QLineEdit(tab);
        editLineScore->setObjectName(QStringLiteral("editLineScore"));
        editLineScore->setGeometry(QRect(300, 380, 42, 20));
        editLineScore->setAlignment(Qt::AlignCenter);
        editHoughThetaMaxSub = new QLineEdit(tab);
        editHoughThetaMaxSub->setObjectName(QStringLiteral("editHoughThetaMaxSub"));
        editHoughThetaMaxSub->setEnabled(false);
        editHoughThetaMaxSub->setGeometry(QRect(70, 550, 42, 20));
        editHoughThetaMaxSub->setAlignment(Qt::AlignCenter);
        editHoughThreshold = new QLineEdit(tab);
        editHoughThreshold->setObjectName(QStringLiteral("editHoughThreshold"));
        editHoughThreshold->setGeometry(QRect(79, 503, 42, 20));
        editHoughThreshold->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(tab);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(9, 475, 61, 20));
        label_10->setFont(font4);
        label_10->setFrameShape(QFrame::NoFrame);
        label_10->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(9, 505, 61, 20));
        label_7->setFont(font4);
        label_7->setFrameShape(QFrame::NoFrame);
        label_7->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        labelVoteAvg = new QLabel(tab);
        labelVoteAvg->setObjectName(QStringLiteral("labelVoteAvg"));
        labelVoteAvg->setGeometry(QRect(129, 503, 42, 20));
        labelVoteAvg->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelVoteAvg->setFrameShape(QFrame::Box);
        labelVoteAvg->setAlignment(Qt::AlignCenter);
        editVoidThreshold = new QLineEdit(tab);
        editVoidThreshold->setObjectName(QStringLiteral("editVoidThreshold"));
        editVoidThreshold->setGeometry(QRect(79, 473, 42, 20));
        editVoidThreshold->setAlignment(Qt::AlignCenter);
        editHoughThetaMinSub = new QLineEdit(tab);
        editHoughThetaMinSub->setObjectName(QStringLiteral("editHoughThetaMinSub"));
        editHoughThetaMinSub->setEnabled(false);
        editHoughThetaMinSub->setGeometry(QRect(20, 550, 42, 20));
        editHoughThetaMinSub->setAlignment(Qt::AlignCenter);
        checkSubImage = new QCheckBox(tab);
        checkSubImage->setObjectName(QStringLiteral("checkSubImage"));
        checkSubImage->setEnabled(false);
        checkSubImage->setGeometry(QRect(30, 530, 101, 17));
        editHoughThetaStepSub = new QLineEdit(tab);
        editHoughThetaStepSub->setObjectName(QStringLiteral("editHoughThetaStepSub"));
        editHoughThetaStepSub->setEnabled(false);
        editHoughThetaStepSub->setGeometry(QRect(120, 550, 42, 20));
        editHoughThetaStepSub->setAlignment(Qt::AlignCenter);
        readWeldSeamBox = new QCheckBox(tab);
        readWeldSeamBox->setObjectName(QStringLiteral("readWeldSeamBox"));
        readWeldSeamBox->setGeometry(QRect(370, 320, 201, 17));
        readWeldSeamBox->setFont(font2);
        readMachineStatusBox = new QCheckBox(tab);
        readMachineStatusBox->setObjectName(QStringLiteral("readMachineStatusBox"));
        readMachineStatusBox->setGeometry(QRect(370, 280, 211, 17));
        readMachineStatusBox->setFont(font2);
        readDistanceBox = new QCheckBox(tab);
        readDistanceBox->setObjectName(QStringLiteral("readDistanceBox"));
        readDistanceBox->setGeometry(QRect(370, 300, 201, 17));
        readDistanceBox->setFont(font2);
        label_15 = new QLabel(tab);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(360, 250, 231, 101));
        label_15->setFont(font);
        label_15->setFrameShape(QFrame::Box);
        label_15->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        alignGuideBox = new QCheckBox(tab);
        alignGuideBox->setObjectName(QStringLiteral("alignGuideBox"));
        alignGuideBox->setGeometry(QRect(370, 460, 211, 17));
        alignGuideBox->setFont(font2);
        zctrlBox = new QCheckBox(tab);
        zctrlBox->setObjectName(QStringLiteral("zctrlBox"));
        zctrlBox->setEnabled(false);
        zctrlBox->setGeometry(QRect(370, 360, 141, 17));
        zctrlBox->setFont(font2);
        hardControlStartBox = new QCheckBox(tab);
        hardControlStartBox->setObjectName(QStringLiteral("hardControlStartBox"));
        hardControlStartBox->setGeometry(QRect(370, 420, 171, 17));
        hardControlStartBox->setFont(font2);
        dynamicAlgoBox = new QCheckBox(tab);
        dynamicAlgoBox->setObjectName(QStringLiteral("dynamicAlgoBox"));
        dynamicAlgoBox->setEnabled(false);
        dynamicAlgoBox->setGeometry(QRect(370, 380, 161, 17));
        dynamicAlgoBox->setFont(font2);
        widthControlBox = new QCheckBox(tab);
        widthControlBox->setObjectName(QStringLiteral("widthControlBox"));
        widthControlBox->setGeometry(QRect(370, 400, 161, 17));
        widthControlBox->setFont(font2);
        timeControlBox = new QCheckBox(tab);
        timeControlBox->setObjectName(QStringLiteral("timeControlBox"));
        timeControlBox->setGeometry(QRect(370, 440, 161, 17));
        timeControlBox->setFont(font2);
        label_16 = new QLabel(tab);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(420, 630, 111, 20));
        label_16->setFont(font4);
        label_16->setFrameShape(QFrame::NoFrame);
        label_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_13 = new QLabel(tab);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(420, 570, 111, 20));
        label_13->setFont(font4);
        label_13->setFrameShape(QFrame::NoFrame);
        label_13->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        editIPI = new QLineEdit(tab);
        editIPI->setObjectName(QStringLiteral("editIPI"));
        editIPI->setGeometry(QRect(370, 598, 42, 20));
        editIPI->setMaxLength(2);
        editIPI->setAlignment(Qt::AlignCenter);
        editVideoDuration = new QLineEdit(tab);
        editVideoDuration->setObjectName(QStringLiteral("editVideoDuration"));
        editVideoDuration->setGeometry(QRect(370, 628, 42, 20));
        editVideoDuration->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(tab);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(420, 600, 131, 20));
        label_14->setFont(font4);
        label_14->setFrameShape(QFrame::NoFrame);
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        editFPS = new QLineEdit(tab);
        editFPS->setObjectName(QStringLiteral("editFPS"));
        editFPS->setGeometry(QRect(370, 568, 42, 20));
        editFPS->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(tab);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 270, 101, 20));
        QFont font5;
        font5.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font5.setPointSize(8);
        font5.setBold(true);
        font5.setWeight(75);
        label_22->setFont(font5);
        label_22->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        label_22->setFrameShape(QFrame::NoFrame);
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        twoPassWeldingBox = new QCheckBox(tab);
        twoPassWeldingBox->setObjectName(QStringLiteral("twoPassWeldingBox"));
        twoPassWeldingBox->setGeometry(QRect(370, 480, 211, 17));
        twoPassWeldingBox->setFont(font2);
        autoDetect2ndPassBox = new QCheckBox(tab);
        autoDetect2ndPassBox->setObjectName(QStringLiteral("autoDetect2ndPassBox"));
        autoDetect2ndPassBox->setGeometry(QRect(370, 500, 211, 17));
        autoDetect2ndPassBox->setFont(font2);
        tabWidget->addTab(tab, QString());
        label_15->raise();
        plainTextEdit->raise();
        clearButton->raise();
        labelMainEdgesNumber->raise();
        label_19->raise();
        label_21->raise();
        gaussSizeSlider->raise();
        label_9->raise();
        lineDetectionBox->raise();
        editHoughThetaMax->raise();
        radioWoLaser->raise();
        algorithmBox->raise();
        radioLaser->raise();
        mainEdgesSlider->raise();
        cannyThinningBox->raise();
        label_8->raise();
        labelGaussSDev->raise();
        label_20->raise();
        editHoughLineNo->raise();
        labelGaussSize->raise();
        editHoughThetaStep->raise();
        gaussSDevSlider->raise();
        label_6->raise();
        editHoughThetaMin->raise();
        editLineScore->raise();
        editHoughThetaMaxSub->raise();
        editHoughThreshold->raise();
        label_10->raise();
        label_7->raise();
        labelVoteAvg->raise();
        editVoidThreshold->raise();
        editHoughThetaMinSub->raise();
        checkSubImage->raise();
        editHoughThetaStepSub->raise();
        readWeldSeamBox->raise();
        readMachineStatusBox->raise();
        readDistanceBox->raise();
        alignGuideBox->raise();
        zctrlBox->raise();
        hardControlStartBox->raise();
        dynamicAlgoBox->raise();
        widthControlBox->raise();
        timeControlBox->raise();
        label_16->raise();
        label_13->raise();
        editIPI->raise();
        editVideoDuration->raise();
        label_14->raise();
        editFPS->raise();
        label_22->raise();
        twoPassWeldingBox->raise();
        autoDetect2ndPassBox->raise();
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        graphicsView = new QGraphicsView(tab_2);
        graphicsView->setObjectName(QStringLiteral("graphicsView"));
        graphicsView->setGeometry(QRect(3, 0, 600, 200));
        sizePolicy.setHeightForWidth(graphicsView->sizePolicy().hasHeightForWidth());
        graphicsView->setSizePolicy(sizePolicy);
        graphicsView->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView2 = new QGraphicsView(tab_2);
        graphicsView2->setObjectName(QStringLiteral("graphicsView2"));
        graphicsView2->setGeometry(QRect(3, 310, 600, 200));
        sizePolicy.setHeightForWidth(graphicsView2->sizePolicy().hasHeightForWidth());
        graphicsView2->setSizePolicy(sizePolicy);
        graphicsView2->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView2->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView3 = new QGraphicsView(tab_2);
        graphicsView3->setObjectName(QStringLiteral("graphicsView3"));
        graphicsView3->setGeometry(QRect(3, 512, 600, 200));
        sizePolicy.setHeightForWidth(graphicsView3->sizePolicy().hasHeightForWidth());
        graphicsView3->setSizePolicy(sizePolicy);
        graphicsView3->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView3->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        labelTarget2 = new QLabel(tab_2);
        labelTarget2->setObjectName(QStringLiteral("labelTarget2"));
        labelTarget2->setGeometry(QRect(3, 205, 600, 100));
        labelTarget2->setFrameShape(QFrame::Box);
        labelTarget2->setScaledContents(true);
        tabWidget->addTab(tab_2, QString());
        label_23 = new QLabel(setupForm);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(729, 377, 121, 15));
        label_23->setFont(font5);
        label_23->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        label_23->setFrameShape(QFrame::NoFrame);
        label_23->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        imgParametersButton = new QPushButton(setupForm);
        imgParametersButton->setObjectName(QStringLiteral("imgParametersButton"));
        imgParametersButton->setGeometry(QRect(10, 495, 211, 25));
        imgParametersButton->setFont(font4);
        testButton = new QPushButton(setupForm);
        testButton->setObjectName(QStringLiteral("testButton"));
        testButton->setGeometry(QRect(290, 530, 41, 25));
        testButton->setFont(font);
        label_24 = new QLabel(setupForm);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(-7, 586, 81, 20));
        label_24->setFont(font1);
        label_24->setFrameShape(QFrame::NoFrame);
        label_24->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        maFilterSizeSlider = new QSlider(setupForm);
        maFilterSizeSlider->setObjectName(QStringLiteral("maFilterSizeSlider"));
        maFilterSizeSlider->setGeometry(QRect(83, 586, 160, 22));
        maFilterSizeSlider->setAutoFillBackground(false);
        maFilterSizeSlider->setMinimum(1);
        maFilterSizeSlider->setMaximum(50);
        maFilterSizeSlider->setSingleStep(5);
        maFilterSizeSlider->setValue(1);
        maFilterSizeSlider->setSliderPosition(1);
        maFilterSizeSlider->setTracking(true);
        maFilterSizeSlider->setOrientation(Qt::Horizontal);
        maFilterSizeSlider->setInvertedAppearance(false);
        maFilterSizeSlider->setInvertedControls(false);
        maFilterSizeSlider->setTickPosition(QSlider::TicksBothSides);
        maFilterSizeSlider->setTickInterval(5);
        labelMAFilterSize = new QLabel(setupForm);
        labelMAFilterSize->setObjectName(QStringLiteral("labelMAFilterSize"));
        labelMAFilterSize->setGeometry(QRect(252, 586, 42, 20));
        labelMAFilterSize->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelMAFilterSize->setFrameShape(QFrame::Box);
        labelMAFilterSize->setAlignment(Qt::AlignCenter);
        histogramAnalysisButton = new QPushButton(setupForm);
        histogramAnalysisButton->setObjectName(QStringLiteral("histogramAnalysisButton"));
        histogramAnalysisButton->setGeometry(QRect(10, 530, 91, 25));
        histogramAnalysisButton->setFont(font);
        label_25 = new QLabel(setupForm);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(23, 636, 51, 20));
        label_25->setFont(font1);
        label_25->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        label_25->setFrameShape(QFrame::NoFrame);
        label_25->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        histAngleSlider = new QSlider(setupForm);
        histAngleSlider->setObjectName(QStringLiteral("histAngleSlider"));
        histAngleSlider->setGeometry(QRect(83, 636, 160, 22));
        histAngleSlider->setAutoFillBackground(false);
        histAngleSlider->setMinimum(1);
        histAngleSlider->setMaximum(30);
        histAngleSlider->setSingleStep(5);
        histAngleSlider->setValue(1);
        histAngleSlider->setSliderPosition(1);
        histAngleSlider->setTracking(true);
        histAngleSlider->setOrientation(Qt::Horizontal);
        histAngleSlider->setInvertedAppearance(false);
        histAngleSlider->setInvertedControls(false);
        histAngleSlider->setTickPosition(QSlider::TicksBothSides);
        histAngleSlider->setTickInterval(5);
        labelHistAngle = new QLabel(setupForm);
        labelHistAngle->setObjectName(QStringLiteral("labelHistAngle"));
        labelHistAngle->setGeometry(QRect(252, 636, 42, 20));
        labelHistAngle->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelHistAngle->setFrameShape(QFrame::Box);
        labelHistAngle->setAlignment(Qt::AlignCenter);
        radioGray = new QRadioButton(setupForm);
        colorGrayGroup = new QButtonGroup(setupForm);
        colorGrayGroup->setObjectName(QStringLiteral("colorGrayGroup"));
        colorGrayGroup->addButton(radioGray);
        radioGray->setObjectName(QStringLiteral("radioGray"));
        radioGray->setGeometry(QRect(200, 530, 61, 21));
        radioGray->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        radioColored = new QRadioButton(setupForm);
        colorGrayGroup->addButton(radioColored);
        radioColored->setObjectName(QStringLiteral("radioColored"));
        radioColored->setGeometry(QRect(120, 530, 71, 21));
        radioColored->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        radioColored->setChecked(true);
        label_26 = new QLabel(setupForm);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(24, 662, 111, 20));
        label_26->setFont(font1);
        label_26->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        label_26->setFrameShape(QFrame::NoFrame);
        label_26->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        lenRateThrSlider = new QSlider(setupForm);
        lenRateThrSlider->setObjectName(QStringLiteral("lenRateThrSlider"));
        lenRateThrSlider->setGeometry(QRect(144, 662, 100, 22));
        lenRateThrSlider->setAutoFillBackground(false);
        lenRateThrSlider->setMinimum(20);
        lenRateThrSlider->setMaximum(100);
        lenRateThrSlider->setSingleStep(25);
        lenRateThrSlider->setValue(25);
        lenRateThrSlider->setSliderPosition(25);
        lenRateThrSlider->setTracking(true);
        lenRateThrSlider->setOrientation(Qt::Horizontal);
        lenRateThrSlider->setInvertedAppearance(false);
        lenRateThrSlider->setInvertedControls(false);
        lenRateThrSlider->setTickPosition(QSlider::TicksBothSides);
        lenRateThrSlider->setTickInterval(20);
        labellenRateThr = new QLabel(setupForm);
        labellenRateThr->setObjectName(QStringLiteral("labellenRateThr"));
        labellenRateThr->setGeometry(QRect(252, 662, 42, 20));
        labellenRateThr->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labellenRateThr->setFrameShape(QFrame::Box);
        labellenRateThr->setAlignment(Qt::AlignCenter);
        bandWidthMinSlider = new QSlider(setupForm);
        bandWidthMinSlider->setObjectName(QStringLiteral("bandWidthMinSlider"));
        bandWidthMinSlider->setGeometry(QRect(144, 688, 100, 22));
        bandWidthMinSlider->setAutoFillBackground(false);
        bandWidthMinSlider->setMinimum(10);
        bandWidthMinSlider->setMaximum(100);
        bandWidthMinSlider->setSingleStep(25);
        bandWidthMinSlider->setValue(25);
        bandWidthMinSlider->setSliderPosition(25);
        bandWidthMinSlider->setTracking(true);
        bandWidthMinSlider->setOrientation(Qt::Horizontal);
        bandWidthMinSlider->setInvertedAppearance(false);
        bandWidthMinSlider->setInvertedControls(false);
        bandWidthMinSlider->setTickPosition(QSlider::TicksBothSides);
        bandWidthMinSlider->setTickInterval(20);
        label_27 = new QLabel(setupForm);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(34, 688, 101, 20));
        label_27->setFont(font1);
        label_27->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        label_27->setFrameShape(QFrame::NoFrame);
        label_27->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        labelBandWidthMin = new QLabel(setupForm);
        labelBandWidthMin->setObjectName(QStringLiteral("labelBandWidthMin"));
        labelBandWidthMin->setGeometry(QRect(252, 688, 42, 20));
        labelBandWidthMin->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelBandWidthMin->setFrameShape(QFrame::Box);
        labelBandWidthMin->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(setupForm);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(294, 689, 31, 20));
        label_28->setFont(font1);
        label_28->setFrameShape(QFrame::NoFrame);
        label_28->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        bandCenterMaxSlider = new QSlider(setupForm);
        bandCenterMaxSlider->setObjectName(QStringLiteral("bandCenterMaxSlider"));
        bandCenterMaxSlider->setGeometry(QRect(144, 714, 100, 22));
        bandCenterMaxSlider->setAutoFillBackground(false);
        bandCenterMaxSlider->setMinimum(1);
        bandCenterMaxSlider->setMaximum(10);
        bandCenterMaxSlider->setSingleStep(25);
        bandCenterMaxSlider->setValue(10);
        bandCenterMaxSlider->setSliderPosition(10);
        bandCenterMaxSlider->setTracking(true);
        bandCenterMaxSlider->setOrientation(Qt::Horizontal);
        bandCenterMaxSlider->setInvertedAppearance(false);
        bandCenterMaxSlider->setInvertedControls(false);
        bandCenterMaxSlider->setTickPosition(QSlider::TicksBothSides);
        bandCenterMaxSlider->setTickInterval(20);
        label_29 = new QLabel(setupForm);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(14, 714, 121, 20));
        label_29->setFont(font1);
        label_29->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        label_29->setFrameShape(QFrame::NoFrame);
        label_29->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        label_30 = new QLabel(setupForm);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(294, 715, 31, 20));
        label_30->setFont(font1);
        label_30->setFrameShape(QFrame::NoFrame);
        label_30->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        labelBandCenterMax = new QLabel(setupForm);
        labelBandCenterMax->setObjectName(QStringLiteral("labelBandCenterMax"));
        labelBandCenterMax->setGeometry(QRect(252, 714, 42, 20));
        labelBandCenterMax->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelBandCenterMax->setFrameShape(QFrame::Box);
        labelBandCenterMax->setAlignment(Qt::AlignCenter);
        histAreaNoSlider = new QSlider(setupForm);
        histAreaNoSlider->setObjectName(QStringLiteral("histAreaNoSlider"));
        histAreaNoSlider->setGeometry(QRect(144, 560, 100, 22));
        histAreaNoSlider->setAutoFillBackground(false);
        histAreaNoSlider->setMinimum(1);
        histAreaNoSlider->setMaximum(9);
        histAreaNoSlider->setSingleStep(2);
        histAreaNoSlider->setPageStep(4);
        histAreaNoSlider->setValue(1);
        histAreaNoSlider->setSliderPosition(1);
        histAreaNoSlider->setTracking(true);
        histAreaNoSlider->setOrientation(Qt::Horizontal);
        histAreaNoSlider->setInvertedAppearance(false);
        histAreaNoSlider->setInvertedControls(false);
        histAreaNoSlider->setTickPosition(QSlider::TicksBothSides);
        histAreaNoSlider->setTickInterval(2);
        labelHistAreaNo = new QLabel(setupForm);
        labelHistAreaNo->setObjectName(QStringLiteral("labelHistAreaNo"));
        labelHistAreaNo->setGeometry(QRect(252, 560, 42, 20));
        labelHistAreaNo->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelHistAreaNo->setFrameShape(QFrame::Box);
        labelHistAreaNo->setAlignment(Qt::AlignCenter);
        label_31 = new QLabel(setupForm);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(24, 560, 111, 20));
        label_31->setFont(font1);
        label_31->setFrameShape(QFrame::NoFrame);
        label_31->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        regionBox = new QComboBox(setupForm);
        regionBox->setObjectName(QStringLiteral("regionBox"));
        regionBox->setGeometry(QRect(10, 560, 41, 23));
        labelhistCornerPrec = new QLabel(setupForm);
        labelhistCornerPrec->setObjectName(QStringLiteral("labelhistCornerPrec"));
        labelhistCornerPrec->setEnabled(false);
        labelhistCornerPrec->setGeometry(QRect(252, 611, 42, 20));
        labelhistCornerPrec->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        labelhistCornerPrec->setFrameShape(QFrame::Box);
        labelhistCornerPrec->setAlignment(Qt::AlignCenter);
        label_32 = new QLabel(setupForm);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setEnabled(false);
        label_32->setGeometry(QRect(14, 611, 121, 20));
        label_32->setFont(font1);
        label_32->setFrameShape(QFrame::NoFrame);
        label_32->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        histCornerPrecSlider = new QSlider(setupForm);
        histCornerPrecSlider->setObjectName(QStringLiteral("histCornerPrecSlider"));
        histCornerPrecSlider->setEnabled(false);
        histCornerPrecSlider->setGeometry(QRect(144, 611, 100, 22));
        histCornerPrecSlider->setAutoFillBackground(false);
        histCornerPrecSlider->setMinimum(0);
        histCornerPrecSlider->setMaximum(20);
        histCornerPrecSlider->setSingleStep(25);
        histCornerPrecSlider->setValue(0);
        histCornerPrecSlider->setSliderPosition(0);
        histCornerPrecSlider->setTracking(true);
        histCornerPrecSlider->setOrientation(Qt::Horizontal);
        histCornerPrecSlider->setInvertedAppearance(false);
        histCornerPrecSlider->setInvertedControls(false);
        histCornerPrecSlider->setTickPosition(QSlider::TicksBothSides);
        histCornerPrecSlider->setTickInterval(20);
        tabWidget->raise();
        labelTarget->raise();
        labelMono->raise();
        labelEdge->raise();
        labelHough->raise();
        labelAnalyze->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        label_5->raise();
        captureButton->raise();
        saveButton->raise();
        labelPrimaryLine->raise();
        saveExitButton->raise();
        exitButton->raise();
        line_2->raise();
        captureButton_2->raise();
        brightnessSlider->raise();
        labelBrightness->raise();
        contrastSlider->raise();
        labelContrast->raise();
        gammaSlider->raise();
        labelGamma->raise();
        brightnessReset->raise();
        contrastReset->raise();
        gammaReset->raise();
        fileSlider->raise();
        checkProcessing->raise();
        edgeDetectionBox->raise();
        label_11->raise();
        label_17->raise();
        label_18->raise();
        cameraEnhancementsBox->raise();
        captureNext->raise();
        capturePrev->raise();
        debugModeBox->raise();
        labelPicNo->raise();
        label_23->raise();
        imgParametersButton->raise();
        testButton->raise();
        label_24->raise();
        maFilterSizeSlider->raise();
        labelMAFilterSize->raise();
        histogramAnalysisButton->raise();
        label_25->raise();
        histAngleSlider->raise();
        labelHistAngle->raise();
        radioGray->raise();
        radioColored->raise();
        label_26->raise();
        lenRateThrSlider->raise();
        labellenRateThr->raise();
        bandWidthMinSlider->raise();
        label_27->raise();
        labelBandWidthMin->raise();
        label_28->raise();
        bandCenterMaxSlider->raise();
        label_29->raise();
        label_30->raise();
        labelBandCenterMax->raise();
        histAreaNoSlider->raise();
        labelHistAreaNo->raise();
        label_31->raise();
        regionBox->raise();
        labelhistCornerPrec->raise();
        label_32->raise();
        histCornerPrecSlider->raise();

        retranslateUi(setupForm);
        QObject::connect(captureButton, SIGNAL(clicked()), setupForm, SLOT(captureButton()));
        QObject::connect(saveButton, SIGNAL(clicked()), setupForm, SLOT(saveButton()));
        QObject::connect(clearButton, SIGNAL(clicked()), setupForm, SLOT(clearButton()));
        QObject::connect(exitButton, SIGNAL(clicked()), setupForm, SLOT(exitButton()));
        QObject::connect(saveExitButton, SIGNAL(clicked()), setupForm, SLOT(saveExitButton()));
        QObject::connect(checkSubImage, SIGNAL(clicked()), setupForm, SLOT(subImageCheck()));
        QObject::connect(zctrlBox, SIGNAL(stateChanged(int)), setupForm, SLOT(zctrlBox()));
        QObject::connect(hardControlStartBox, SIGNAL(stateChanged(int)), setupForm, SLOT(hardControlStartBox()));
        QObject::connect(widthControlBox, SIGNAL(stateChanged(int)), setupForm, SLOT(widthControl()));
        QObject::connect(readMachineStatusBox, SIGNAL(stateChanged(int)), setupForm, SLOT(readMachineStatusBox()));
        QObject::connect(readDistanceBox, SIGNAL(stateChanged(int)), setupForm, SLOT(readDistanceBox()));
        QObject::connect(dynamicAlgoBox, SIGNAL(stateChanged(int)), setupForm, SLOT(dynamicAlgoBox()));
        QObject::connect(readWeldSeamBox, SIGNAL(stateChanged(int)), setupForm, SLOT(readWeldSeamBox()));
        QObject::connect(timeControlBox, SIGNAL(stateChanged(int)), setupForm, SLOT(timeControlBox()));
        QObject::connect(lineDetectionBox, SIGNAL(stateChanged(int)), setupForm, SLOT(lineDetectionBox()));
        QObject::connect(editLineScore, SIGNAL(returnPressed()), setupForm, SLOT(editLineScore()));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(setupForm);
    } // setupUi

    void retranslateUi(QWidget *setupForm)
    {
        setupForm->setWindowTitle(QApplication::translate("setupForm", "Kurulum Ayarlar\304\261", 0));
        labelTarget->setText(QString());
        labelMono->setText(QString());
        labelEdge->setText(QString());
        labelHough->setText(QString());
        labelAnalyze->setText(QString());
        label->setText(QApplication::translate("setupForm", "Hedef Alan \304\260maj\304\261", 0));
        label_2->setText(QApplication::translate("setupForm", "Mono/Kontrast \304\260maj", 0));
        label_3->setText(QApplication::translate("setupForm", "Tespit Edilen Kenarlar", 0));
        label_4->setText(QApplication::translate("setupForm", "\303\207izgi Tespiti", 0));
        label_5->setText(QApplication::translate("setupForm", "K\303\266\305\237e Tespiti", 0));
        captureButton->setText(QApplication::translate("setupForm", "Analiz", 0));
        saveButton->setText(QApplication::translate("setupForm", "Kaydet", 0));
        labelPrimaryLine->setText(QApplication::translate("setupForm", "\303\207\304\260ZG\304\260 BULUNAMIYOR!", 0));
        saveExitButton->setText(QApplication::translate("setupForm", "\303\207\304\261k/Kaydet", 0));
        exitButton->setText(QApplication::translate("setupForm", "\303\207\304\261k", 0));
        captureButton_2->setText(QApplication::translate("setupForm", "Resim Y\303\274kle", 0));
        labelBrightness->setText(QApplication::translate("setupForm", "0", 0));
        labelContrast->setText(QApplication::translate("setupForm", "0", 0));
        labelGamma->setText(QApplication::translate("setupForm", "0", 0));
        brightnessReset->setText(QApplication::translate("setupForm", "R", 0));
        contrastReset->setText(QApplication::translate("setupForm", "R", 0));
        gammaReset->setText(QApplication::translate("setupForm", "R", 0));
        checkProcessing->setText(QApplication::translate("setupForm", "Analiz Aktif", 0));
        edgeDetectionBox->clear();
        edgeDetectionBox->insertItems(0, QStringList()
         << QApplication::translate("setupForm", "Yok", 0)
         << QApplication::translate("setupForm", "Sobel", 0)
         << QApplication::translate("setupForm", "Canny4", 0)
         << QApplication::translate("setupForm", "Canny1", 0)
        );
        label_11->setText(QApplication::translate("setupForm", "Parlakl\304\261k", 0));
        label_17->setText(QApplication::translate("setupForm", "Kontrast", 0));
        label_18->setText(QApplication::translate("setupForm", "Gamma", 0));
#ifndef QT_NO_TOOLTIP
        cameraEnhancementsBox->setToolTip(QApplication::translate("setupForm", "Kaynak ba\305\237lang\304\261c\304\261ndaki geni\305\237li\304\237in %80 ile %120 si aras\304\261n\304\261 ge\303\247erli say", 0));
#endif // QT_NO_TOOLTIP
        cameraEnhancementsBox->setText(QApplication::translate("setupForm", "Kamera", 0));
        captureNext->setText(QApplication::translate("setupForm", "+", 0));
        capturePrev->setText(QApplication::translate("setupForm", "-", 0));
#ifndef QT_NO_TOOLTIP
        debugModeBox->setToolTip(QApplication::translate("setupForm", "Kaynak ba\305\237lang\304\261c\304\261ndaki geni\305\237li\304\237in %80 ile %120 si aras\304\261n\304\261 ge\303\247erli say", 0));
#endif // QT_NO_TOOLTIP
        debugModeBox->setText(QApplication::translate("setupForm", "DEBUG", 0));
        labelPicNo->setText(QApplication::translate("setupForm", "No", 0));
        plainTextEdit->setDocumentTitle(QString());
        plainTextEdit->setPlainText(QString());
        clearButton->setText(QApplication::translate("setupForm", "Temizle", 0));
        labelMainEdgesNumber->setText(QApplication::translate("setupForm", "0", 0));
        label_19->setText(QApplication::translate("setupForm", "Denoise Genlik", 0));
        label_21->setText(QApplication::translate("setupForm", "Ana Kenar Say\304\261s\304\261", 0));
        label_9->setText(QApplication::translate("setupForm", "A\303\247\304\261 Aral\304\261\304\237\304\261", 0));
#ifndef QT_NO_TOOLTIP
        lineDetectionBox->setToolTip(QApplication::translate("setupForm", "\304\260KA ya Otomaik Ge\303\247", 0));
#endif // QT_NO_TOOLTIP
        lineDetectionBox->setText(QApplication::translate("setupForm", "\303\207izgi Tespiti (%)", 0));
        editHoughThetaMax->setInputMask(QApplication::translate("setupForm", "999", 0));
        editHoughThetaMax->setText(QApplication::translate("setupForm", "93", 0));
        radioWoLaser->setText(QApplication::translate("setupForm", "Lazersiz Takip", 0));
        algorithmBox->clear();
        algorithmBox->insertItems(0, QStringList()
         << QApplication::translate("setupForm", "0", 0)
         << QApplication::translate("setupForm", "1", 0)
        );
        radioLaser->setText(QApplication::translate("setupForm", "Lazerli Takip", 0));
#ifndef QT_NO_TOOLTIP
        cannyThinningBox->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        cannyThinningBox->setText(QApplication::translate("setupForm", "Canny \304\260nceltme", 0));
        label_8->setText(QApplication::translate("setupForm", "A\303\247\304\261 \303\207\303\266z.", 0));
        labelGaussSDev->setText(QApplication::translate("setupForm", "0", 0));
        label_20->setText(QApplication::translate("setupForm", "Denoise Sapma", 0));
        editHoughLineNo->setInputMask(QApplication::translate("setupForm", "999", 0));
        editHoughLineNo->setText(QApplication::translate("setupForm", "2", 0));
        labelGaussSize->setText(QApplication::translate("setupForm", "0", 0));
        editHoughThetaStep->setInputMask(QApplication::translate("setupForm", "9.9", 0));
        editHoughThetaStep->setText(QApplication::translate("setupForm", "1.0", 0));
        label_6->setText(QApplication::translate("setupForm", "\303\207izgi Say\304\261s\304\261", 0));
        editHoughThetaMin->setInputMask(QApplication::translate("setupForm", "#999", 0));
        editHoughThetaMin->setText(QApplication::translate("setupForm", "87", 0));
        editLineScore->setInputMask(QApplication::translate("setupForm", "99", 0));
        editLineScore->setText(QApplication::translate("setupForm", "0", 0));
        editHoughThetaMaxSub->setInputMask(QApplication::translate("setupForm", "999", 0));
        editHoughThetaMaxSub->setText(QApplication::translate("setupForm", "100", 0));
        editHoughThreshold->setInputMask(QApplication::translate("setupForm", "999", 0));
        editHoughThreshold->setText(QApplication::translate("setupForm", "200", 0));
        label_10->setText(QApplication::translate("setupForm", "Void E\305\237i\304\237i", 0));
        label_7->setText(QApplication::translate("setupForm", "Vote E\305\237i\304\237i", 0));
        labelVoteAvg->setText(QApplication::translate("setupForm", "Avg", 0));
        editVoidThreshold->setInputMask(QApplication::translate("setupForm", "99", 0));
        editVoidThreshold->setText(QApplication::translate("setupForm", "30", 0));
        editHoughThetaMinSub->setInputMask(QApplication::translate("setupForm", "999", 0));
        editHoughThetaMinSub->setText(QApplication::translate("setupForm", "80", 0));
        checkSubImage->setText(QApplication::translate("setupForm", "Alt \304\260maj", 0));
        editHoughThetaStepSub->setInputMask(QApplication::translate("setupForm", "9.9", 0));
        editHoughThetaStepSub->setText(QApplication::translate("setupForm", "1.0", 0));
#ifndef QT_NO_TOOLTIP
        readWeldSeamBox->setToolTip(QApplication::translate("setupForm", "DB2.DB0.x", 0));
#endif // QT_NO_TOOLTIP
        readWeldSeamBox->setText(QApplication::translate("setupForm", "Kaynak \304\260zi  Bilgisi", 0));
#ifndef QT_NO_TOOLTIP
        readMachineStatusBox->setToolTip(QApplication::translate("setupForm", "DB2.DB0.x", 0));
#endif // QT_NO_TOOLTIP
        readMachineStatusBox->setText(QApplication::translate("setupForm", "Makine \303\207al\304\261\305\237ma Durumu Bilgisi", 0));
#ifndef QT_NO_TOOLTIP
        readDistanceBox->setToolTip(QApplication::translate("setupForm", "DBX.DBW2", 0));
#endif // QT_NO_TOOLTIP
        readDistanceBox->setText(QApplication::translate("setupForm", "Mesafe Bilgisi", 0));
        label_15->setText(QApplication::translate("setupForm", "PLC B\304\260LG\304\260", 0));
#ifndef QT_NO_TOOLTIP
        alignGuideBox->setToolTip(QApplication::translate("setupForm", "Makineden Kaynak Ba\305\237lang\304\261c\304\261", 0));
#endif // QT_NO_TOOLTIP
        alignGuideBox->setText(QApplication::translate("setupForm", "Kaynak Ba\305\237lang\304\261c\304\261nda Hizala", 0));
        zctrlBox->setText(QApplication::translate("setupForm", "Y\303\274kseklik Kontrol\303\274", 0));
#ifndef QT_NO_TOOLTIP
        hardControlStartBox->setToolTip(QApplication::translate("setupForm", "Makineden Kaynak Ba\305\237lang\304\261c\304\261", 0));
#endif // QT_NO_TOOLTIP
        hardControlStartBox->setText(QApplication::translate("setupForm", "Hard Kaynak Ba\305\237lang\304\261c\304\261", 0));
#ifndef QT_NO_TOOLTIP
        dynamicAlgoBox->setToolTip(QApplication::translate("setupForm", "\304\260KA ya Otomaik Ge\303\247", 0));
#endif // QT_NO_TOOLTIP
        dynamicAlgoBox->setText(QApplication::translate("setupForm", "Dinamik Algoritma", 0));
#ifndef QT_NO_TOOLTIP
        widthControlBox->setToolTip(QApplication::translate("setupForm", "Kaynak ba\305\237lang\304\261c\304\261ndaki geni\305\237li\304\237in %80 ile %120 si aras\304\261n\304\261 ge\303\247erli say", 0));
#endif // QT_NO_TOOLTIP
        widthControlBox->setText(QApplication::translate("setupForm", "Geni\305\237lik Kontrol\303\274", 0));
#ifndef QT_NO_TOOLTIP
        timeControlBox->setToolTip(QApplication::translate("setupForm", "<html><head/><body><p>Belirli bir s\303\274re sonra kaynak komutlar\304\261n\304\261 kes</p></body></html>", 0));
#endif // QT_NO_TOOLTIP
        timeControlBox->setText(QApplication::translate("setupForm", "Zaman Kontrol\303\274", 0));
        label_16->setText(QApplication::translate("setupForm", "Kay\304\261t S\303\274resi (sn)", 0));
        label_13->setText(QApplication::translate("setupForm", "FPS", 0));
        editIPI->setInputMask(QApplication::translate("setupForm", "99", 0));
        editIPI->setText(QApplication::translate("setupForm", "3", 0));
        editVideoDuration->setInputMask(QApplication::translate("setupForm", "99", 0));
        editVideoDuration->setText(QApplication::translate("setupForm", "1", 0));
        label_14->setText(QApplication::translate("setupForm", "\304\260maj \304\260\305\237leme Aral\304\261\304\237\304\261", 0));
        editFPS->setInputMask(QApplication::translate("setupForm", "999", 0));
        editFPS->setText(QApplication::translate("setupForm", "10", 0));
        label_22->setText(QApplication::translate("setupForm", "ALGOR\304\260TMA", 0));
#ifndef QT_NO_TOOLTIP
        twoPassWeldingBox->setToolTip(QApplication::translate("setupForm", "Makineden Kaynak Ba\305\237lang\304\261c\304\261", 0));
#endif // QT_NO_TOOLTIP
        twoPassWeldingBox->setText(QApplication::translate("setupForm", "2 Paso Uygulamas\304\261", 0));
#ifndef QT_NO_TOOLTIP
        autoDetect2ndPassBox->setToolTip(QApplication::translate("setupForm", "Makineden Kaynak Ba\305\237lang\304\261c\304\261", 0));
#endif // QT_NO_TOOLTIP
        autoDetect2ndPassBox->setText(QApplication::translate("setupForm", "2.Pasoya Oto Ge\303\247i\305\237", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("setupForm", "Ayarlar", 0));
        labelTarget2->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("setupForm", "Grafik", 0));
        label_23->setText(QApplication::translate("setupForm", "KENAR TESP\304\260T", 0));
        imgParametersButton->setText(QApplication::translate("setupForm", "\304\260maj Parametrelerini Hesapla", 0));
        testButton->setText(QApplication::translate("setupForm", "Test", 0));
        label_24->setText(QApplication::translate("setupForm", "MAF Genlik", 0));
        labelMAFilterSize->setText(QApplication::translate("setupForm", "0", 0));
        histogramAnalysisButton->setText(QApplication::translate("setupForm", "Hist Analizi", 0));
        label_25->setText(QApplication::translate("setupForm", "A\303\247\304\261", 0));
        labelHistAngle->setText(QApplication::translate("setupForm", "0", 0));
        radioGray->setText(QApplication::translate("setupForm", "Gri", 0));
        radioColored->setText(QApplication::translate("setupForm", "Renkli", 0));
        label_26->setText(QApplication::translate("setupForm", "\303\207izgi Oran\304\261 E\305\237i\304\237i", 0));
        labellenRateThr->setText(QApplication::translate("setupForm", "0", 0));
        label_27->setText(QApplication::translate("setupForm", "Band Gen Min", 0));
        labelBandWidthMin->setText(QApplication::translate("setupForm", "0", 0));
        label_28->setText(QApplication::translate("setupForm", "%", 0));
        label_29->setText(QApplication::translate("setupForm", "Band Merkezi Max", 0));
        label_30->setText(QApplication::translate("setupForm", "%", 0));
        labelBandCenterMax->setText(QApplication::translate("setupForm", "0", 0));
        labelHistAreaNo->setText(QApplication::translate("setupForm", "1", 0));
        label_31->setText(QApplication::translate("setupForm", "B\303\266lge Say\304\261s\304\261", 0));
        labelhistCornerPrec->setText(QApplication::translate("setupForm", "0", 0));
        label_32->setText(QApplication::translate("setupForm", "K\303\266\305\237e Tespit Has.", 0));
    } // retranslateUi

};

namespace Ui {
    class setupForm: public Ui_setupForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SETUPFORM_H
